### PR TITLE
Add info on cp-remote data sharing.

### PR DESCRIPTION
**Pull request by pswaine**

### CODE REVIEW

**Comment by sroze** [comment]
what do you think of that @tonypiper ?

**Comment by pswaine** [comment]
@tonypiper - any chance you can review this data sharing disclaimer?

**Comment by tonypiper** [comment]
looks good to me - wonder if @andytson-inviqa has any comments. 

If I'm a user I guess I want to know if I can opt out, and whether any of this stuff can be used to steal/compromise my code/environments.

**Comment by andytson-inviqa** [comment]
it's something that should either be opt-in, or on installation/first use the user is told, and told how to opt out

**Pull request merged**
