### PR TITLE
Diagrams to represent tide execution and filtering.

### PR DESCRIPTION
**Pull request by pswaine**

### CODE REVIEW

**Comment by sroze** [comment]
Love the style of the diagrams! Two things tho:

1. The Docker & Kubernetes credentials are actually related to the project. They are only used by the flow.
screen shot 2017-04-07 at 12 59 21

2. For both the pipeline and non-pipeline, these different tide can create the same environment or different ones!
screen shot 2017-04-07 at 12 59 15

Also, I don't need if you omitted it for simplicity but the tasks filter also works with the pipeline, in addition to the pipeline filters 😉

**Comment by pswaine** [comment]
> The Docker & Kubernetes credentials are actually related to the project. They are only used by the flow.
👍 I'll get it updated

> For both the pipeline and non-pipeline, these different tide can create the same environment or different ones!
I'll have a think how I can represent that...

> Also, I don't need if you omitted it for simplicity but the tasks filter also works with the pipeline, in addition to the pipeline filters
Yes, omitted for simplicity - thats why its split into two diagrams. Also, even though you can combine pipeline filters and task filters, *should* you actually combine them? Are there situations where that happens?

**Comment by pswaine** [comment]
@sroze :
1 - updated
2 - I'm not sure how to add that without adding extra complexity - if its ok I'll leave as it is for now and think about it
3 - I've added a note

also - I corrected a mistake in the pipelines diagram - it should have been tasks, not tides below the pipeline.

**Comment by sroze** [comment]
👍 👌

**Pull request merged**
